package com.johnsosoka.selfdiscover.config;

import com.johnsosoka.selfdiscover.agent.SelfDiscoverAgent;
import com.johnsosoka.selfdiscover.agent.SolverAgent;
import dev.langchain4j.model.chat.ChatLanguageModel;
import dev.langchain4j.service.AiServices;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class SelfDiscoveryAgentConfig {

    /**
     * Provisions an AIService `SelfDiscoverAgent` which contains the prompts
     * which implement the SELF-DISCOVER algorithm to self-compose reasoning structures.
     * @param chatLanguageModel
     * @return
     */
    @Bean
    public SelfDiscoverAgent selfDiscoveryAgent(ChatLanguageModel chatLanguageModel) {
        return AiServices.builder(SelfDiscoverAgent.class)
                .chatLanguageModel(chatLanguageModel)
                .build();
    }

    /**
     * Provisions an AIService `SolverAgent` which contains the prompts for solving a given task.
     * The self-composed reasoning structures generated by the SelfDiscover Agent  are used to
     * solve the task.
     *
     * @param chatLanguageModel
     * @return
     */
    @Bean
    public SolverAgent solverAgent(ChatLanguageModel chatLanguageModel) {
        return AiServices.builder(SolverAgent.class)
                .chatLanguageModel(chatLanguageModel)
                .build();
    }
}
